services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: data-etl-api
    ports:
      - "8090:8090"
    volumes:
      - .:/app
      - /appdata/storage:/storage
      # - uv-cache:/root/.cache/uv  # UV 캐시 볼륨 추가
    environment:
      - PYTHONPATH=/app
      - UV_CACHE_DIR=/app/.cache/uv
    user: "1000:1000"
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8090 --reload

volumes:
  uv-cache:  # UV 캐시를 위한 볼륨 정의 