from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Float
from sqlalchemy.orm import relationship
from app.db.base import Base
from datetime import datetime
from typing import Optional
from app.schemas.eiu_schemas import EIUDataType
class EconomicData(Base):
    """경제 데이터 모델 - EIU 데이터 저장"""
    __tablename__ = "tb_rhr100"
    
    eiu_cont_en_nm = Column(String(200), index=True, comment="EIU국가영문명")
    eiu_country_code = Column(String(2), primary_key=True, index=True, comment="EIU국가코드")
    eiu_currency = Column(String(10), comment="EIU통화명")
    eiu_series_title = Column(String(350), comment="EIU시리즈제목")
    eiu_code = Column(String(50), primary_key=True, index=True, comment="EIU코드")
    eiu_units = Column(String(30), nullable=True, comment="EIU단위")
    # 연도별 데이터 (19년부터 51년까지)
    eiu_year1 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2001년")
    eiu_year2 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2002년")
    eiu_year3 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2003년")
    eiu_year4 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2004년")
    eiu_year5 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2005년")
    eiu_year6 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2006년")
    eiu_year7 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2007년")
    eiu_year8 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2008년")
    eiu_year9 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2009년")
    eiu_year10 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2010년")
    eiu_year11 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2011년")
    eiu_year12 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2012년")
    eiu_year13 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2013년")
    eiu_year14 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2014년")
    eiu_year15 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2015년")
    eiu_year16 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2016년")
    eiu_year17 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2017년")
    eiu_year18 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2018년")
    eiu_year19 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment ="2019년")
    eiu_year20 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2020년")
    eiu_year21 = Column(String(300), nullable=True, default=EIUDataType.UNKNOWN.value,comment="2021년")
    eiu_year22 = Column(String(300), nullable=True, comment="2022년")
    eiu_year23 = Column(String(300), nullable=True, comment="2023년")
    eiu_year24 = Column(String(300), nullable=True, comment="2024년")
    eiu_year25 = Column(String(300), nullable=True, comment="2025년")
    eiu_year26 = Column(String(300), nullable=True, comment="2026년")
    eiu_year27 = Column(String(300), nullable=True, comment="2027년")
    eiu_year28 = Column(String(300), nullable=True, comment="2028년")
    eiu_year29 = Column(String(300), nullable=True, comment="2029년")
    eiu_year30 = Column(String(300), nullable=True, comment="2030년")
    eiu_year31 = Column(String(300), nullable=True, comment="2031년")
    eiu_year32 = Column(String(300), nullable=True, comment="2032년")
    eiu_year33 = Column(String(300), nullable=True, comment="2033년")
    eiu_year34 = Column(String(300), nullable=True, comment="2034년")
    eiu_year35 = Column(String(300), nullable=True, comment="2035년")
    eiu_year36 = Column(String(300), nullable=True, comment="2036년")
    eiu_year37 = Column(String(300), nullable=True, comment="2037년")
    eiu_year38 = Column(String(300), nullable=True, comment="2038년")
    eiu_year39 = Column(String(300), nullable=True, comment="2039년")
    eiu_year40 = Column(String(300), nullable=True, comment="2040년")
    eiu_year41 = Column(String(300), nullable=True, comment="2041년")
    eiu_year42 = Column(String(300), nullable=True, comment="2042년")
    eiu_year43 = Column(String(300), nullable=True, comment="2043년")
    eiu_year44 = Column(String(300), nullable=True, comment="2044년")
    eiu_year45 = Column(String(300), nullable=True, comment="2045년")
    eiu_year46 = Column(String(300), nullable=True, comment="2046년")
    eiu_year47 = Column(String(300), nullable=True, comment="2047년")
    eiu_year48 = Column(String(300), nullable=True, comment="2048년")
    eiu_year49 = Column(String(300), nullable=True, comment="2049년")
    eiu_year50 = Column(String(300), nullable=True, comment="2050년")
    eiu_year51 = Column(String(300), nullable=True, comment="2051년")
    created_at = Column(DateTime, default=datetime.now, comment="생성일")
    updated_at = Column(DateTime, default=datetime.now, comment="수정일")

class COUNTRY_INFO(Base):
    __tablename__ = "tw_rhm_ria010"
    
    trgtpsn_no = Column(String(10), primary_key=True, index=True, comment="대상국가번호")
    trgtpsn_nm = Column(String(300), comment="대상국가명")
    trgtpsn_abbr_nm = Column(String(300), comment="대상국가약칭")
    use_yn = Column(String(1), comment="사용여부")
    rgn_cd = Column(String(3), comment="지역코드")
    trgtpsn_eng_nm = Column(String(300), comment="대상국가영문명")
    trgtpsn_eng_abbr_nm = Column(String(300), comment="대상국가영문약칭")
    trgtpsn_sct_cd = Column(String(1), comment="대상국가구분코드")
    fmty_ctry_nm = Column(String(300), comment="대상국가명")
    loc_ctnt = Column(String(300), comment="대상국가위치")
    trtry_area_ctnt = Column(String(300), comment="대상국가지역")
    clmt_ctnt = Column(String(300), comment="대상국가기후")
    ppltn_ctnt = Column(String(300), comment="대상국가인구")
    cpt_nm = Column(String(300), comment="대상국가명")
    race_ctnt = Column(String(300), comment="대상국가인종")
    lang_nm = Column(String(300), comment="대상국가언어")
    relgn_nm = Column(String(300), comment="대상국가종교")
    idpnc_ctnt = Column(String(300), comment="대상국가문화")
    govrn_frm_ctnt = Column(String(300), comment="대상국가정치체제")
    ctry_chfstate_nm = Column(String(300), comment="대상국가주요상태")
    ntlasm_ctnt = Column(String(300), comment="대상국가국가코드")
    main_pltclpty_ctnt = Column(String(300), comment="대상국가주요도시")
    gdp_ctnt = Column(String(300), comment="대상국가GDP")
    perpsn_gdp_ctnt = Column(String(300), comment="대상국가인구당GDP")
    mny_unit_ctnt = Column(String(300), comment="대상국가통화단위")
    fscyl_base_yymm = Column(String(6), comment="대상국가기준년월")
    inds_str_ctnt = Column(String(300), comment="대상국가산업구조")
    edwrsc_ctnt = Column(String(300), comment="대상국가경제구조")
    byecn_strpnt_ctnt = Column(String(1000), comment="대상국가주요정책")
    byecn_wkpnt_ctnt = Column(String(1000), comment="대상국가주요정책")
    dpmcy_afl_estb_dd = Column(String(8), comment="대상국가주요정책")
    trd_scl_ctnt = Column(String(1000), comment="대상국가주요정책")
    main_trd_artc_ctnt = Column(String(1000), comment="대상국가주요정책")
    main_expctry_ctnt = Column(String(1000), comment="대상국가주요정책")
    main_impctry_ctnt = Column(String(1000), comment="대상국가주요정책")
    curr_cd = Column(String(5), comment="대상국가주요정책")
    ntr_dstr_ctnt = Column(String(1500), comment="대상국가주요정책")
    unempl_rt_ctnt = Column(String(300), comment="대상국가주요정책")
    trgtpsn_reg_dtm = Column(String(14), comment="대상국가주요정책")
    trgtpsn_cd = Column(String(3), comment="대상국가주요정책")
    std_infrm_ctry_cd = Column(String(2), comment="대상국가주요정책")
    oecd_entry_yn = Column(String(1), comment="대상국가주요정책")