from sqlalchemy import Column, String
from app.db.base import Base

class COUNTRY_INFO(Base):
    __tablename__ = "tw_rhm_ria010"
    
    trgtpsn_no = Column(String(10), primary_key=True, index=True, comment="대상국가번호")
    trgtpsn_nm = Column(String(300), comment="대상국가명")
    trgtpsn_abbr_nm = Column(String(300), comment="대상국가약칭")
    use_yn = Column(String(1), comment="사용여부")
    rgn_cd = Column(String(3), comment="지역코드")
    trgtpsn_eng_nm = Column(String(300), comment="대상국가영문명")
    trgtpsn_eng_abbr_nm = Column(String(300), comment="대상국가영문약칭")
    trgtpsn_sct_cd = Column(String(1), comment="대상국가구분코드")
    fmty_ctry_nm = Column(String(300), comment="대상국가명")
    loc_ctnt = Column(String(300), comment="대상국가위치")
    trtry_area_ctnt = Column(String(300), comment="대상국가지역")
    clmt_ctnt = Column(String(300), comment="대상국가기후")
    ppltn_ctnt = Column(String(300), comment="대상국가인구")
    cpt_nm = Column(String(300), comment="대상국가명")
    race_ctnt = Column(String(300), comment="대상국가인종")
    lang_nm = Column(String(300), comment="대상국가언어")
    relgn_nm = Column(String(300), comment="대상국가종교")
    idpnc_ctnt = Column(String(300), comment="대상국가문화")
    govrn_frm_ctnt = Column(String(300), comment="대상국가정치체제")
    ctry_chfstate_nm = Column(String(300), comment="대상국가주요상태")
    ntlasm_ctnt = Column(String(300), comment="대상국가국가코드")
    main_pltclpty_ctnt = Column(String(300), comment="대상국가주요도시")
    gdp_ctnt = Column(String(300), comment="대상국가GDP")
    perpsn_gdp_ctnt = Column(String(300), comment="대상국가인구당GDP")
    mny_unit_ctnt = Column(String(300), comment="대상국가통화단위")
    fscyl_base_yymm = Column(String(6), comment="대상국가기준년월")
    inds_str_ctnt = Column(String(300), comment="대상국가산업구조")
    edwrsc_ctnt = Column(String(300), comment="대상국가경제구조")
    byecn_strpnt_ctnt = Column(String(1000), comment="대상국가주요정책")
    byecn_wkpnt_ctnt = Column(String(1000), comment="대상국가주요정책")
    dpmcy_afl_estb_dd = Column(String(8), comment="대상국가주요정책")
    trd_scl_ctnt = Column(String(1000), comment="대상국가주요정책")
    main_trd_artc_ctnt = Column(String(1000), comment="대상국가주요정책")
    main_expctry_ctnt = Column(String(1000), comment="대상국가주요정책")
    main_impctry_ctnt = Column(String(1000), comment="대상국가주요정책")
    curr_cd = Column(String(5), comment="대상국가주요정책")
    ntr_dstr_ctnt = Column(String(1500), comment="대상국가주요정책")
    unempl_rt_ctnt = Column(String(300), comment="대상국가주요정책")
    trgtpsn_reg_dtm = Column(String(14), comment="대상국가주요정책")
    trgtpsn_cd = Column(String(3), comment="대상국가주요정책")
    std_infrm_ctry_cd = Column(String(2), comment="대상국가주요정책")
    oecd_entry_yn = Column(String(1), comment="대상국가주요정책")

class CountryMapping(Base):
    __tablename__ = "tb_rhr350"

    eng_ctry_nm = Column(String(200), primary_key=True, nullable=True, comment="영문국가명")
    std_infrm_ctry_cd = Column(String(2), primary_key=True, nullable=True, comment="표준약식국가코드")
    kcs_kor_ctry_nm = Column(String(100), comment="관세청한글국가명")